// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module "vue" {
  export interface GlobalComponents {
    ElButton: typeof import("element-plus/es")["ElButton"];
    ElContainer: typeof import("element-plus/es")["ElContainer"];
    ElForm: typeof import("element-plus/es")["ElForm"];
    ElFormItem: typeof import("element-plus/es")["ElFormItem"];
    ElHeader: typeof import("element-plus/es")["ElHeader"];
    ElInput: typeof import("element-plus/es")["ElInput"];
    ElInputNumber: typeof import("element-plus/es")["ElInputNumber"];
    ElMain: typeof import("element-plus/es")["ElMain"];
    ElMenu: typeof import("element-plus/es")["ElMenu"];
    ElMenuItem: typeof import("element-plus/es")["ElMenuItem"];
    ElOption: typeof import("element-plus/es")["ElOption"];
    ElRow: typeof import("element-plus/es")["ElRow"];
    ElSelect: typeof import("element-plus/es")["ElSelect"];
    ElTable: typeof import("element-plus/es")["ElTable"];
    ElTableColumn: typeof import("element-plus/es")["ElTableColumn"];
    HelloWorld: typeof import("./src/components/HelloWorld.vue")["default"];
    IconCommunity: typeof import("./src/components/icons/IconCommunity.vue")["default"];
    IconDocumentation: typeof import("./src/components/icons/IconDocumentation.vue")["default"];
    IconEcosystem: typeof import("./src/components/icons/IconEcosystem.vue")["default"];
    IconSupport: typeof import("./src/components/icons/IconSupport.vue")["default"];
    IconTooling: typeof import("./src/components/icons/IconTooling.vue")["default"];
    TheWelcome: typeof import("./src/components/TheWelcome.vue")["default"];
    WelcomeItem: typeof import("./src/components/WelcomeItem.vue")["default"];
  }
}

export {};
